#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if hash apt-get >/dev/null 2>&1; then
    echo "Now modify /etc/php5/fpm/pool.d/www.conf to listen on 127.0.0.1:9000."
    echo "And then run: sudo service php5-fpm restart"
    echo
    echo "If you are running Chrome OS, edit script/server to run nginx as sudo"
    sleep 1s
fi
